// Catalogo esemplari della rete (oltre ai canonici di N.4/N.6/VILLA).
import type { Specimen } from "./canon";

export const networkSpecimens: Specimen[] = [
  // --- N.2 Perù · ragni ---
  { id: "11C", codiceEsteso: "1-01-C-ATC", specie: "Ragno saltatore", gen: 1, protocollo: "C", coscienza: false, nomeProprio: "Illari", branch: "new", facilityId: "N2", stato: "attivo", note: "Prima linea salticide con acuità degli occhi principali estesa nel vicino ultravioletto. Discrimina pattern di riflettanza su prede immobili a distanza doppia rispetto al ceppo selvatico. Baseline sensoriale della coorte C." },
  { id: "12D", codiceEsteso: "1-02-D-GCA", specie: "Tarantola", gen: 1, protocollo: "D", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N2", stato: "attivo", note: "Emolinfa arricchita di peptidi antimicrobici che riduce la mortalità da infezione fungina in cattività. Sopravvive a esposizioni a spore di Ophiocordyceps letali nei controlli." },
  { id: "21C", codiceEsteso: "2-01-C-TAC", specie: "Ragno saltatore", gen: 2, protocollo: "C", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N2", stato: "attivo", note: "Densità aumentata di fotorecettori nella retina a strati. Migliore separazione cromatica nel verde-rosso, utile a valutare il trasferimento del tratto sensoriale tra covate." },
  { id: "22D", codiceEsteso: "2-02-D-CGT", specie: "Tarantola", gen: 2, protocollo: "D", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N2", stato: "baseline", note: "Ceppo di controllo per la resistenza ai nematodi entomopatogeni; risposta immunitaria cellulare più rapida ma fecondità invariata." },
  { id: "31C", codiceEsteso: "3-01-C-ATG", specie: "Ragno saltatore", gen: 3, protocollo: "C", coscienza: false, nomeProprio: "Amaru", branch: "new", facilityId: "N2", stato: "attivo", note: "Individuo notevole per soglia di rilevamento del movimento estremamente bassa. Nessun segno di flessibilità comportamentale oltre il repertorio predatorio tipico dei salticidi." },
  { id: "32D", codiceEsteso: "3-02-D-GGT", specie: "Tarantola", gen: 3, protocollo: "D", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N2", stato: "proposto", note: "Coorte proposta per combinare resistenza fungina e batterica in un unico profilo emocitario. In valutazione per stabilità del tratto tra le mute." },

  // --- N.3 Giappone · anfibi ---
  { id: "11B", codiceEsteso: "1-01-B-CAT", specie: "Axolotl", gen: 1, protocollo: "B", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N3", stato: "attivo", note: "Linea fondativa con rigenerazione degli arti accelerata e tolleranza termica fino a 24 °C senza perdita del neotenismo. Cicatrizzazione epidermica priva di fibrosi anche a temperature elevate." },
  { id: "12G", codiceEsteso: "1-02-G-TCA", specie: "Axolotl", gen: 1, protocollo: "G", coscienza: false, nomeProprio: "Yuki", branch: "new", facilityId: "N3", stato: "attivo", note: "Formazione del blastema più rapida del 30% dopo amputazione dell'arto anteriore. Individuo di riferimento per l'imaging longitudinale della rigenerazione." },
  { id: "21B", codiceEsteso: "2-01-B-ACG", specie: "Salamandra", gen: 2, protocollo: "B", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N3", stato: "attivo", note: "Rigenerazione dermica pigmentata: i motivi cromatici si ricostituiscono fedelmente dopo lesione. Utile a studiare il ripristino del pattern melanoforico." },
  { id: "22G", codiceEsteso: "2-02-G-GTA", specie: "Tritone", gen: 2, protocollo: "G", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N3", stato: "attivo", note: "Selezionato per rigenerazione del tessuto cardiaco dopo lesione ventricolare controllata, oltre alla ricrescita degli arti. Modello per la riparazione miocardica senza cicatrice." },
  { id: "31B", codiceEsteso: "3-01-B-CGA", specie: "Axolotl", gen: 3, protocollo: "B", coscienza: false, nomeProprio: "Haruki", branch: "new", facilityId: "N3", stato: "attivo", note: "Neotenia stabile su tre generazioni con soppressione affidabile della metamorfosi. Combina rigenerazione e resistenza allo stress termico; candidato al trasferimento crioconservato verso N1." },
  { id: "32G", codiceEsteso: "3-02-G-ATA", specie: "Salamandra", gen: 3, protocollo: "G", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N3", stato: "baseline", note: "Baseline muscoloscheletrica: ricrescita di falangi multiple in sequenza senza malformazioni. Bassa variabilità inter-individuale." },

  // --- N.4 Italia · iguane ---
  { id: "13B", codiceEsteso: "1-03-B-TGC", specie: "Iguana verde", gen: 1, protocollo: "B", coscienza: false, nomeProprio: null, branch: "47b", facilityId: "N4", stato: "attivo", note: "Ramo iguana a bassa generazione con termoregolazione comportamentale più efficiente e viraggio cromatico dorsale accentuato. Profilo comportamentale nella norma per la specie." },
  { id: "14C", codiceEsteso: "1-04-C-CAG", specie: "Iguana verde", gen: 1, protocollo: "C", coscienza: false, nomeProprio: null, branch: "47b", facilityId: "N4", stato: "attivo", note: "Occhio parietale più sensibile con miglior discriminazione della luce polarizzata, utile all'orientamento. Profilo comportamentale tipico della specie." },
  { id: "23B", codiceEsteso: "2-03-B-GAT", specie: "Iguana verde", gen: 2, protocollo: "B", coscienza: false, nomeProprio: null, branch: "47b", facilityId: "N4", stato: "attivo", note: "Guarigione delle ferite cutanee accelerata e minore perdita di calore notturna. Metabolismo basale ottimizzato per il clima delle serre italiane." },
  { id: "24C", codiceEsteso: "2-04-C-ATT", specie: "Iguana verde", gen: 2, protocollo: "C", coscienza: false, nomeProprio: null, branch: "47b", facilityId: "N4", stato: "attivo", note: "Acuità visiva cromatica ampliata e maggiore responsività ai segnali gulari conspecifici. Interazioni sociali marcate ma prive di indicatori di autoconsapevolezza." },
  { id: "51B", codiceEsteso: "5-01-B-CTG", specie: "Iguana verde", gen: 5, protocollo: "B", coscienza: null, nomeProprio: "Nerina", branch: "47b", facilityId: "N4", stato: "attivo", note: "Linea avanzata prossima al ramo 47B; episodi ambigui di fissazione prolungata verso lo specchio, mai riprodotti in modo controllato. Flag comportamentale indeterminato, in attesa di validazione." },
  { id: "52C", codiceEsteso: "5-02-C-GCT", specie: "Iguana verde", gen: 5, protocollo: "C", coscienza: false, nomeProprio: null, branch: "47b", facilityId: "N4", stato: "attivo", note: "Mappa sensoriale integrata vista-olfatto ma nessuna deviazione cognitiva rilevata. Serve da controllo negativo rispetto alle linee comportamentalmente anomale." },

  // --- N.5 India · serpenti ---
  { id: "13D", codiceEsteso: "1-03-D-TAC", specie: "Cobra reale", gen: 1, protocollo: "D", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N5", stato: "attivo", note: "Elapide fondativo con resistenza aumentata alle infezioni respiratorie da micobatteri. Titolo anticorpale basale più alto senza alterazioni della composizione del veleno." },
  { id: "14F", codiceEsteso: "1-04-F-CGA", specie: "Vipera", gen: 1, protocollo: "F", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N5", stato: "attivo", note: "Selezionato per tolleranza all'ipossia durante brumazione prolungata; sopravvive a lunghi periodi a bassa ossigenazione con ridotta acidosi tissutale." },
  { id: "23D", codiceEsteso: "2-03-D-ATG", specie: "Cobra reale", gen: 2, protocollo: "D", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N5", stato: "attivo", note: "Clearance più rapida di endoparassiti gastrointestinali. Crescita regolare e resa riproduttiva stabile, adatta all'espansione della colonia." },
  { id: "24F", codiceEsteso: "2-04-F-GTC", specie: "Vipera", gen: 2, protocollo: "F", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N5", stato: "attivo", note: "Frequenza cardiaca in dormienza abbassabile in modo reversibile su comando termico, con recupero neurologico completo al risveglio. Riferimento per protocolli di trasporto." },
  { id: "33D", codiceEsteso: "3-03-D-TGA", specie: "Cobra reale", gen: 3, protocollo: "D", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N5", stato: "baseline", note: "Baseline immunitaria con ampio repertorio di peptidi antimicrobici cutanei. Usato per calibrare i saggi di resistenza patogeni." },
  { id: "34F", codiceEsteso: "3-04-F-CAT", specie: "Vipera", gen: 3, protocollo: "F", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N5", stato: "proposto", note: "Coorte proposta per combinare ipossia-tolleranza e riduzione del fabbisogno metabolico invernale. In valutazione per gli effetti sulla fertilità." },

  // --- N.6 Polonia · varani ---
  { id: "71G", codiceEsteso: "7-01-G-GTA", specie: "Varano", gen: 7, protocollo: "G", coscienza: false, nomeProprio: "Halina", branch: "varani", facilityId: "N6", stato: "attivo", note: "Programma varani maturo: rigenerazione parziale della coda con ricostituzione ossea vertebrale, non solo cartilaginea. Massa muscolare degli arti superiore alla media." },
  { id: "72F", codiceEsteso: "7-02-F-ACG", specie: "Varano", gen: 7, protocollo: "F", coscienza: false, nomeProprio: null, branch: "varani", facilityId: "N6", stato: "attivo", note: "Tolleranza all'ipossia durante immersioni prolungate con bradicardia da immersione pronunciata. Riserve di mioglobina elevate." },
  { id: "81G", codiceEsteso: "8-01-G-TCG", specie: "Varano", gen: 8, protocollo: "G", coscienza: false, nomeProprio: null, branch: "varani", facilityId: "N6", stato: "attivo", note: "Guarigione delle fratture accelerata e rimodellamento osseo denso. Candidato al trasferimento verso N10 come asset di validazione muscoloscheletrica." },
  { id: "82F", codiceEsteso: "8-02-F-GAC", specie: "Varano", gen: 8, protocollo: "F", coscienza: false, nomeProprio: null, branch: "varani", facilityId: "N6", stato: "ceduto", note: "Ceduto per dormienza metabolica controllata di lunga durata con recupero completo della funzione epatica. Documentazione di trasferimento condivisa con la struttura di validazione." },
  { id: "92G", codiceEsteso: "9-02-G-CTA", specie: "Varano", gen: 9, protocollo: "G", coscienza: null, nomeProprio: "Zbigniew", branch: "varani", facilityId: "N6", stato: "attivo", note: "Occasionali comportamenti di problem-solving nel recupero del cibo, non distinguibili con certezza dall'apprendimento associativo. Flag comportamentale indeterminato." },
  { id: "93F", codiceEsteso: "9-03-F-AGT", specie: "Varano", gen: 9, protocollo: "F", coscienza: false, nomeProprio: null, branch: "varani", facilityId: "N6", stato: "attivo", note: "Massima efficienza di dormienza del programma polacco: consumo energetico ridotto in torpore stagionale senza perdita muscolare misurabile." },

  // --- N.7 Indonesia · rettili marini ---
  { id: "11E", codiceEsteso: "1-01-E-GTC", specie: "Tartaruga marina", gen: 1, protocollo: "E", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N7", stato: "attivo", note: "Linea fondativa con ghiandole del sale sovraciliari più efficienti, che consentono bilancio idrico stabile a salinità elevate." },
  { id: "12H", codiceEsteso: "1-02-H-CAG", specie: "Tartaruga marina", gen: 1, protocollo: "H", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N7", stato: "attivo", note: "Marcatori di senescenza cellulare ridotti e mantenimento telomerico prolungato. Crescita lenta ma continua tipica dei cheloni longevi." },
  { id: "21E", codiceEsteso: "2-01-E-ATC", specie: "Serpente marino", gen: 2, protocollo: "E", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N7", stato: "attivo", note: "Idrofide con ghiandola sublinguale del sale potenziata e assorbimento cutaneo di ossigeno migliorato. Bilancio osmotico stabile in acqua marina piena." },
  { id: "22H", codiceEsteso: "2-02-H-TGA", specie: "Tartaruga marina", gen: 2, protocollo: "H", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N7", stato: "baseline", note: "Baseline di longevità con basso danno ossidativo tissutale e riparazione cartilaginea articolare efficiente." },
  { id: "31E", codiceEsteso: "3-01-E-GCA", specie: "Tartaruga marina", gen: 3, protocollo: "E", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N7", stato: "proposto", note: "Coorte proposta per unire osmoregolazione robusta e tolleranza a variazioni rapide di salinità negli estuari. In attesa di valutazione della funzione renale." },

  // --- N.8 Uganda · camaleonti ---
  { id: "15B", codiceEsteso: "1-05-B-CGT", specie: "Camaleonte pantera", gen: 1, protocollo: "B", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N8", stato: "attivo", note: "Linea fondativa con controllo più fine dei nanocristalli di guanina negli iridofori, che amplia l'intervallo di viraggio cromatico. Cambiamento di colore più rapido." },
  { id: "16C", codiceEsteso: "1-06-C-TAG", specie: "Camaleonte pantera", gen: 1, protocollo: "C", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N8", stato: "attivo", note: "Coordinazione oculare indipendente potenziata con migliore stima della distanza per la proiezione linguale. Accuratezza di cattura della preda superiore al ceppo selvatico." },
  { id: "25B", codiceEsteso: "2-05-B-GAC", specie: "Camaleonte pantera", gen: 2, protocollo: "B", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N8", stato: "attivo", note: "Segnalazione cromatica sociale più stabile e migliore dissipazione termica per riflettanza dinamica. Comportamento territoriale tipico." },
  { id: "26C", codiceEsteso: "2-06-C-ACT", specie: "Camaleonte pantera", gen: 2, protocollo: "C", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N8", stato: "baseline", note: "Baseline sensoriale con campo visivo panoramico ampliato e ridotto tempo di reazione agli stimoli in movimento." },
  { id: "35B", codiceEsteso: "3-05-B-TCA", specie: "Camaleonte pantera", gen: 3, protocollo: "B", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N8", stato: "attivo", note: "Termoregolazione cromatica ottimizzata per il microclima delle serre ugandesi. Guarigione cutanea rapida con ripristino fedele del pattern pigmentario." },

  // --- N.11 Nuova Caledonia · uccelli ---
  { id: "17C", codiceEsteso: "1-07-C-GTA", specie: "Corvo della Nuova Caledonia", gen: 1, protocollo: "C", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N11", stato: "attivo", note: "Corvide fondativo con acuità visiva e coordinazione occhio-becco potenziate per l'uso di strumenti. Prestazioni cognitive elevate ma entro il repertorio noto della specie selvatica." },
  { id: "18H", codiceEsteso: "1-08-H-CAT", specie: "Pappagallo", gen: 1, protocollo: "H", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N11", stato: "attivo", note: "Linea a longevità estesa con basso tasso di senescenza immunitaria. Piumaggio e funzione epatica stabili nel monitoraggio pluriennale." },
  { id: "27C", codiceEsteso: "2-07-C-AGT", specie: "Corvo della Nuova Caledonia", gen: 2, protocollo: "C", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N11", stato: "attivo", note: "Miglior discriminazione uditiva delle vocalizzazioni conspecifiche. Apprendimento sociale nella norma; nessun indicatore di autoconsapevolezza." },
  { id: "28H", codiceEsteso: "2-08-H-TGC", specie: "Pappagallo", gen: 2, protocollo: "H", coscienza: false, nomeProprio: null, branch: "new", facilityId: "N11", stato: "baseline", note: "Baseline di longevità con marcatori di stress ossidativo ridotti e riparazione telomerica efficiente." },

  // --- N.1 Svizzera · biobanca (linee archiviate) ---
  { id: "46H", codiceEsteso: "4-06-H-CGA", specie: "Iguana verde", gen: 4, protocollo: "H", coscienza: false, nomeProprio: null, branch: "core", facilityId: "N1", stato: "archivio", note: "Linea iguana storica di quarta generazione, crioconservata come riferimento pre-47B per il protocollo longevità." },
  { id: "87A", codiceEsteso: "8-07-A-GAT", specie: "Varano", gen: 8, protocollo: "A", coscienza: false, nomeProprio: null, branch: "core", facilityId: "N1", stato: "archivio", note: "Ceppo varani archiviato per elevata vitalità embrionale e bassa mortalità perinatale. Materiale di partenza per il ripristino della linea." },
  { id: "19A", codiceEsteso: "1-09-A-TAC", specie: "Tarantola", gen: 1, protocollo: "A", coscienza: false, nomeProprio: null, branch: "core", facilityId: "N1", stato: "archivio", note: "Prima linea di ragni crioconservata per validare i protocolli di vitrificazione dell'emolinfa negli aracnidi." },
  { id: "63H", codiceEsteso: "6-03-H-ACG", specie: "Varano", gen: 6, protocollo: "H", coscienza: false, nomeProprio: null, branch: "core", facilityId: "N1", stato: "archivio", note: "Linea varani di sesta generazione conservata come riferimento di longevità precedente ai ceppi più recenti." },

  // --- N.10 USA · asset validati ---
  { id: "74G", codiceEsteso: "7-04-G-GCT", specie: "Varano", gen: 7, protocollo: "G", coscienza: false, nomeProprio: "Bartosz", branch: "varani", facilityId: "N10", stato: "validato", note: "Asset trasferito da N6 e validato negli Stati Uniti per rigenerazione muscoloscheletrica riproducibile. Ricrescita ossea e recupero funzionale confermati in modo indipendente." },
  { id: "86F", codiceEsteso: "8-06-F-CTA", specie: "Varano", gen: 8, protocollo: "F", coscienza: false, nomeProprio: "Wiktoria", branch: "varani", facilityId: "N10", stato: "validato", note: "Esemplare validato per dormienza metabolica controllata, trasferito dal programma polacco. Parametri di torpore e recupero replicati entro tolleranza." }
];
