// Strutture aggiuntive: nodi in costruzione/pianificati/dismessi e sedi di supporto.
import type { Facility } from "./canon";

export const extraFacilities: Facility[] = [
  {
    id: "N12",
    numero: 12,
    nome: "Allevamento N.12",
    paese: "Namibia",
    citta: "Deserto del Namib",
    continente: "Africa",
    lat: -24.75,
    lng: 15.30,
    specie: "Gechi e piccoli rettili del deserto",
    tipo: "allevamento",
    alleva: true,
    tema: "L'Arsura — vita in condizioni aride",
    sommario: "Nuovo allevamento in costruzione dedicato ai rettili adattati agli ambienti iperaridi.",
    descrizione: "Il cantiere dell'Allevamento N.12 è attualmente in corso nel Deserto del Namib. Il sito studierà l'osmoregolazione e la resistenza alla disidratazione in condizioni iperaride. Le strutture sono progettate per riprodurre in modo controllato i regimi termici e igrometrici del deserto. L'apertura operativa è prevista al completamento delle opere e delle validazioni sanitarie.",
    protocolliChiave: ["E", "F"],
    branch: "new",
    stato: "costruzione",
    ordine: 12,
  },
  {
    id: "N13",
    numero: 13,
    nome: "Centro N.13",
    paese: "Cile",
    citta: "Deserto di Atacama",
    continente: "America del Sud",
    lat: -23.85,
    lng: -69.30,
    specie: "Nessuna specie viva; stazione di ricerca su ambienti estremi",
    tipo: "ricerca",
    alleva: false,
    tema: "L'Altopiano — radiazione UV e stress estremo",
    sommario: "Centro di ricerca pianificato per lo studio degli ambienti d'alta quota a forte irraggiamento.",
    descrizione: "Il Centro N.13 è un progetto approvato, con apertura prevista in una fase futura. La sede si concentrerà sugli effetti dell'alta quota, dell'intensa radiazione ultravioletta e delle forti escursioni termiche. Non ospiterà specie vive ma condurrà misurazioni ambientali e prove di laboratorio su campioni e materiali. Il Deserto di Atacama è stato selezionato per le sue condizioni estreme e stabili.",
    protocolliChiave: ["C", "H"],
    branch: "new",
    stato: "pianificata",
    ordine: 13,
  },
  {
    id: "N15",
    numero: 15,
    nome: "Allevamento N.15",
    paese: "Giappone",
    citta: "Okinawa",
    continente: "Asia",
    lat: 26.34,
    lng: 127.80,
    specie: "Rettili marini (linee storiche)",
    tipo: "allevamento",
    alleva: true,
    tema: "La Corrente — sito costiero storico",
    sommario: "Sito costiero storico in fase di chiusura e consolidamento delle attività.",
    descrizione: "L'Allevamento N.15 è in fase di dismissione. Le attività e le linee marine storiche sono in consolidamento verso l'Allevamento N.7 in Indonesia. Il trasferimento avviene in modo graduale, con mantenimento della catena di custodia e degli standard sanitari. Al termine del processo il sito cesserà le operazioni di allevamento.",
    protocolliChiave: ["E", "H"],
    branch: "new",
    stato: "dismissione",
    ordine: 15,
  },
  {
    id: "N16",
    numero: 16,
    nome: "Centro N.16",
    paese: "[ubicazione riservata]",
    citta: "[riservata]",
    continente: "Asia",
    lat: 48.0,
    lng: 66.9,
    specie: "Nessuna specie propria; validazione e prove sul campo",
    tipo: "validazione",
    alleva: false,
    tema: "Il Campo — prove operative",
    sommario: "Secondo sito del Programma Sigma, dedicato a validazione e prove operative, a ubicazione non divulgata.",
    descrizione: "Il Centro N.16 è il secondo sito del Programma Sigma, con ubicazione non divulgata. Si occupa di validazione e integrazione dei risultati, in coordinamento con il Centro N.10. Non dispone di specie proprie e opera principalmente su prove sul campo e verifiche operative. Le coordinate riportate sono approssimate per motivi di riservatezza.",
    protocolliChiave: ["F", "G"],
    branch: "varani",
    stato: "riservato",
    ordine: 16,
  },
  {
    id: "LOG",
    numero: 0,
    nome: "Centro Logistico e Quarantena",
    paese: "Paesi Bassi",
    citta: "Rotterdam",
    continente: "Europa",
    lat: 51.95,
    lng: 4.14,
    specie: "—",
    tipo: "logistica",
    alleva: false,
    tema: "Il Transito — quarantena e movimentazione CITES",
    sommario: "Hub logistico per trasferimenti, quarantena sanitaria e gestione della catena di custodia CITES.",
    descrizione: "Il Centro Logistico e Quarantena funge da hub per i trasferimenti tra i siti della rete. Gestisce la quarantena sanitaria e la catena di custodia CITES per la movimentazione internazionale. La posizione portuale di Rotterdam consente collegamenti efficienti verso le sedi europee ed extraeuropee. La struttura non alleva specie e non compare sulla mappa dei nodi operativi.",
    protocolliChiave: [],
    branch: "core",
    stato: "operativo",
    ordine: 80,
  },
  {
    id: "REGAMER",
    numero: 0,
    nome: "Ufficio Affari Regolatori — Americhe",
    paese: "Stati Uniti",
    citta: "Boston (MA)",
    continente: "America del Nord",
    lat: 42.36,
    lng: -71.06,
    specie: "—",
    tipo: "ufficio",
    alleva: false,
    tema: "La Norma — regolatorio e alleanze",
    sommario: "Ufficio dedicato agli affari regolatori, alla proprietà intellettuale e alle partnership nelle Americhe.",
    descrizione: "L'Ufficio Affari Regolatori per le Americhe cura i rapporti con le autorità competenti della regione. Segue la proprietà intellettuale, le pratiche regolatorie e le partnership istituzionali e commerciali. La sede di Boston consente la vicinanza ai principali poli biotecnologici nordamericani. La struttura svolge funzioni amministrative e non ospita specie.",
    protocolliChiave: [],
    branch: "core",
    stato: "operativo",
    ordine: 81,
  },
  {
    id: "REGAPAC",
    numero: 0,
    nome: "Ufficio Regionale — Asia-Pacifico",
    paese: "Singapore",
    citta: "Singapore",
    continente: "Asia",
    lat: 1.29,
    lng: 103.85,
    specie: "—",
    tipo: "ufficio",
    alleva: false,
    tema: "Il Ponte — coordinamento APAC",
    sommario: "Ufficio regionale per il coordinamento, la compliance e i rapporti istituzionali nell'area Asia-Pacifico.",
    descrizione: "L'Ufficio Regionale Asia-Pacifico coordina le attività della rete nell'area APAC. Segue la compliance normativa e i rapporti con le istituzioni locali e regionali. La sede di Singapore offre un punto di riferimento centrale per i siti asiatici e oceanici. La struttura svolge funzioni di coordinamento e non alleva specie.",
    protocolliChiave: [],
    branch: "core",
    stato: "operativo",
    ordine: 82,
  },
  {
    id: "BIOPROD",
    numero: 0,
    nome: "Impianto Pilota di Bioproduzione",
    paese: "Irlanda",
    citta: "Cork",
    continente: "Europa",
    lat: 51.90,
    lng: -8.47,
    specie: "Nessuna specie viva; scale-up di biomateriali e composti",
    tipo: "bioproduzione",
    alleva: false,
    tema: "La Resa — dalla ricerca alla scala",
    sommario: "Impianto pilota in costruzione per lo scale-up di biomateriali e composti derivati dalla ricerca.",
    descrizione: "L'Impianto Pilota di Bioproduzione è attualmente in costruzione a Cork. Sarà dedicato allo scale-up di biomateriali di seta, peptidi e composti derivati dalla ricerca. L'impianto non ospiterà specie vive e opererà su processi di produzione controllata. L'obiettivo è tradurre i risultati di laboratorio in volumi di scala pilota.",
    protocolliChiave: ["D"],
    branch: "new",
    stato: "costruzione",
    ordine: 83,
  },
  {
    id: "ARCH",
    numero: 0,
    nome: "Archivio Ridondante e Data Recovery",
    paese: "Norvegia",
    citta: "Longyearbyen (Svalbard)",
    continente: "Europa",
    lat: 78.22,
    lng: 15.63,
    specie: "Copia ridondante di linee germinali e dati genomici",
    tipo: "biobanca",
    alleva: false,
    tema: "La Copia — ridondanza dell'archivio",
    sommario: "Copia di sicurezza fredda delle linee germinali e dei dati genomici, in ambiente artico.",
    descrizione: "L'Archivio Ridondante e Data Recovery custodisce una copia di sicurezza fredda della Biobanca N.1 e dell'archivio genomico. La localizzazione artica di Svalbard garantisce condizioni stabili di bassa temperatura e ridondanza geografica. La struttura conserva materiale germinale e dati, senza ospitare specie vive. Le procedure di data recovery assicurano la continuità dell'archivio in caso di perdita al sito primario.",
    protocolliChiave: ["A", "H"],
    branch: "core",
    stato: "operativo",
    ordine: 84,
  },
  {
    id: "FIELD",
    numero: 0,
    nome: "Stazione di Campo — Amazzonia",
    paese: "Brasile",
    citta: "Manaus",
    continente: "America del Sud",
    lat: -3.10,
    lng: -60.02,
    specie: "Studio e raccolta di linee selvatiche di riferimento",
    tipo: "stazione",
    alleva: false,
    tema: "La Fonte — campo e biodiversità",
    sommario: "Stazione di campo per il lavoro in Amazzonia e la raccolta di riferimenti selvatici.",
    descrizione: "La Stazione di Campo Amazzonia svolge lavoro sul campo e raccolta regolare di linee selvatiche di riferimento. Collabora con l'Allevamento N.2 e con l'Allevamento N.7 nella condivisione di campioni e dati di biodiversità. La sede di Manaus offre accesso logistico al bacino amazzonico. La struttura non alleva specie ma opera come base per attività di campo.",
    protocolliChiave: ["C"],
    branch: "new",
    stato: "operativo",
    ordine: 85,
  },
  {
    id: "ZERO",
    numero: 0,
    nome: "Sito Zero — primo laboratorio sperimentale",
    paese: "Italia",
    citta: "Torino",
    continente: "Europa",
    lat: 45.07,
    lng: 7.69,
    specie: "Storico: prime linee (Gen 1), oggi archiviate",
    tipo: "storico",
    alleva: false,
    tema: "L'Origine — sito dismesso",
    sommario: "Primo laboratorio storico dell'azienda, oggi dismesso.",
    descrizione: "Il Sito Zero è stato il primo laboratorio sperimentale dell'azienda. È stato chiuso dopo la Gen 1 e il relativo materiale è stato trasferito alla Biobanca N.1. Le prime linee sviluppate qui sono oggi archiviate e conservate nella rete. La sede non è più operativa e mantiene solo valore storico.",
    protocolliChiave: ["A"],
    branch: "core",
    stato: "dismessa",
    ordine: 86,
  },
  {
    id: "EXMARINE",
    numero: 0,
    nome: "Ex Stazione Marina",
    paese: "Portogallo",
    citta: "Peniche",
    continente: "Europa",
    lat: 39.36,
    lng: -9.38,
    specie: "Storico: primi studi su rettili marini",
    tipo: "storico",
    alleva: false,
    tema: "La Chiusura — attività consolidata in rete",
    sommario: "Ex stazione costiera pilota, dismessa e confluita nei programmi marini della rete.",
    descrizione: "L'Ex Stazione Marina era una stazione costiera pilota dedicata ai primi studi su rettili marini. È stata dismessa e le sue attività sono confluite nei programmi marini della rete. La sede di Peniche ha svolto un ruolo di prova nelle fasi iniziali del lavoro costiero. La struttura non è più operativa.",
    protocolliChiave: ["E"],
    branch: "core",
    stato: "dismessa",
    ordine: 87,
  },
];
